### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/FruityUI#1]
---
> Todo list
---

- [ ] Complete ``Core`` as it does need more work, and ability to create, and manage controls on the fly.
- [ ] Extend most Controls to work properly with FruityUI, and extended for more functionalities/customizations.
- [ ] FruityUI GUI work.
- [ ] Fix potential bugs, memory leaks caused by plugins.
- [ ] Window ContextMenu should work on all controls.
- [ ] FruityUI Icon.
- [ ] FruityUI NotifyIcon, ToolBar, Notifications (Which is another addition to plugins built in with FruityUI)
- [ ] Cleanup, and organize code.
- [ ] Alot of custom controls
- [ ] Alot of plugins
- [ ] Complete in less than 2 weeks.
- [ ] Jump off a bridge after completed.
